# Stacks and heaps
CONFIG_MAIN_STACK_SIZE=3072
CONFIG_HEAP_MEM_POOL_SIZE=16384

# Logging via RTT
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_LOG_BACKEND_RTT=y

CONFIG_DEBUG_OPTIMIZATIONS=y

# Add information for debugging
CONFIG_DEBUG_THREAD_INFO=y

CONFIG_LED=y
