CONFIG_LED=y
CONFIG_ENTROPY_GENERATOR=y

# Gdb related configs
CONFIG_DEBUG_THREAD_INFO=y

# gcc setting
CONFIG_DEBUG_OPTIMIZATIONS=y

#CONFIG_MAIN_THREAD_PRIORITY=10

#CONFIG_INPUT=y
#CONFIG_INPUT_THREAD_PRIORITY_OVERRIDE=y
#CONFIG_INPUT_THREAD_PRIORITY=9
