CONFIG_LED=y
#CONFIG_ENTROPY_GENERATOR=y

# Gdb related configs
CONFIG_DEBUG_THREAD_INFO=y

# gcc setting
CONFIG_DEBUG_OPTIMIZATIONS=y

# k_sleep hangs on the STM32H723ZG
CONFIG_STM32_ENABLE_DEBUG_SLEEP_STOP=y
